name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASS}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
           docker build . --tag $DOCKER_USER/django:v1
           docker push $DOCKERUSER/django:v1
